[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PRIVATE_TARGET = "server"

# [[redirects]]
#   from = "/*"
#   to = "/_next/static/:splat"
#   status = 200
#   force = true
#   conditions = {Path = "/_next/static/*"}