[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.11.0"
  NPM_VERSION = "10.2.4"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Remove the redirects as they are handled by Next.js
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# These settings are handled by Next.js
# [build.processing]
#   skip_processing = false

# [build.processing.css]
#   bundle = true
#   minify = true

# [build.processing.js]
#   bundle = true
#   minify = true

# [build.processing.images]
#   compress = true 