services:
  - type: web
    name: shopifytools
    env: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_DIRECT_URL
        sync: false
      - key: SHOPIFY_APP_API_KEY
        sync: false
      - key: SHOPIFY_APP_SECRET
        sync: false
      - key: SHOPIFY_STORE_DOMAIN
        sync: false
      - key: SHOPIFY_STOREFRONT_ACCESS_TOKEN
        sync: false
    autoDeploy: true
    healthCheckPath: /api/health 